import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "@/contexts/user-context";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-app`}
      >
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}


const colors = {
  "background": "#fff",
  "foreground": "#0f172a",
  "border": "#e6e9ee",
  "input": "#f7f8fa",
  "primary": "#0ea5e9",
  "primary-foreground": "#ffffff",
  "secondary": "#eff8ff",
  "secondary-foreground": "#0369a1",
  "muted": "#e6eef4",
  "muted-foreground": "#475569",
  "success": "#10b981",
  "success-foreground": "#ffffff",
  "accent": "#0ea5e9",
  "accent-foreground": "#ffffff",
  "destructive": "#ef4444",
  "destructive-foreground": "#ffffff",
  "warning": "#f59e0b",
  "warning-foreground": "#ffffff",
  "card": "#ffffff",
  "card-foreground": "#0f172a",
  "sidebar": "#ffffff",
  "sidebar-foreground": "#374151",
  "sidebar-primary": "#e5e7eb",
  "sidebar-primary-foreground": "#0f172a"
}